; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = main

[env:main]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps = 
	esp32async/AsyncTCP@^3.4.10
	esp32async/ESPAsyncWebServer@^3.0.6
board_build.filesystem = littlefs
build_src_filter = +<controller/*>

[env:humidity]
platform = atmelavr
board = attiny85
board_build.mcu = attiny85
board_build.f_cpu = 8000000L
build_src_filter = +<humidity/*>
framework = arduino
lib_extra_dirs = 
	lib/TinyWire/
lib_deps = 
	adafruit/DHT sensor library@^1.4.7

[env:temperature]
platform = atmelavr
board = attiny85
board_build.mcu = attiny85
board_build.f_cpu = 8000000L
build_src_filter = +<temperature/*>
framework = arduino
lib_extra_dirs = 
	lib/TinyWire/
lib_deps = 
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.6
